[package]
name = "kuudos"
version = "0.1.0"
edition = "2018"

[dependencies]
angle = "0.4"
itertools = "0.10"
index_vec = "0.1.3"
num-complex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
rgb = "0.8.27"
simple-xml-builder = "1.0"
vector2d = "2.2"
